FILE_TO_TEST=$1
FUNCTION_TO_TEST=$2
OPERATORS_ALLOWED="1"
PARSED_FILE="parsed_file.txt"
ARGUMENTS_FILE="arguments.txt"

python3 ../src/parse_program.py $FILE_TO_TEST $FUNCTION_TO_TEST $PARSED_FILE $ARGUMENTS_FILE
../src/run_mtt $PARSED_FILE $OPERATORS_ALLOWED $ARGUMENTS_FILE

rm $PARSED_FILE
rm $ARGUMENTS_FILE